### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by abomb14c** [futurice/pepperoni-app-kit#237]
Trying to set up a new pepperoni project and keep getting this when i try to run the app in xcode for the first time after mirroring. Has anyone else run into this? I really don't know how to get around it.

**Comment by tino-junge** [comment]
Hi @abomb14c, thanks for reporting an issue to pepperoni! Just verified it as well with a fresh clone. It seems like a problem of the outdated react-native version the pepperoni-app-it is still using. I'll look into upgrading it soon.

**Comment by grebbekevin** [comment]
Does it have to be updated again?
I am still getting the error:
`The following build commands failed:
	Ld /Users/kevindegroot/Sites/Expo/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/PepperoniAppTemplate normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:607:13)
    at Object.execFileSync (child_process.js:627:13)
    at Promise.then (/Users/kevindegroot/Sites/Expo/pepperoni-app-kit/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>`
