### ISSUE TITLE
Error to build iOS app on fresh clone

### ISSUE THREAD

**Issue by wujiang** [futurice/pepperoni-app-kit#77]
Might related to #25 
### Error:

```
=== BUILD TARGET PepperoniAppTemplate OF PROJECT PepperoniAppTemplate WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock build/Build/Intermediates/PepperoniAppTemplate.build/Debug-iphonesimulator/PepperoniAppTemplate.build/Script-64ECB2A37DD1E0D254C2E832.sh
    cd /tmp/pepperoni-app-kit/ios
    /bin/sh -c /tmp/pepperoni-app-kit/ios/build/Build/Intermediates/PepperoniAppTemplate.build/Debug-iphonesimulator/PepperoniAppTemplate.build/Script-64ECB2A37DD1E0D254C2E832.sh

Ld build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/PepperoniAppTemplate normal x86_64
    cd /tmp/pepperoni-app-kit/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/wjiang/.rvm/gems/ruby-2.3.1/bin:/Users/wjiang/.rvm/gems/ruby-2.3.1@global/bin:/Users/wjiang/.rvm/rubies/ruby-2.3.1/bin:/Users/wjiang/.rvm/bin:/Users/wjiang/.nvm/versions/node/v6.3.0/bin:/Users/wjiang/workspace/go/bin:/usr/local/heroku/bin:/Users/wjiang/.rbenv/shims:/Users/wjiang/.rbenv/shims:/Users/wjiang/.rbenv/bin:/Developer/NVIDIA/CUDA-7.5/bin:/Users/wjiang/opt/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Library/TeX/texbin:/Users/wjiang/opt/android/sdk/tools:/Users/wjiang/opt/android/sdk/platform-tools:/Users/wjiang/workspace/go/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin:/Applications/Android Studio.app/sdk/tools:/Users/wjiang/opt/gradle-2.1/bin:/Users/wjiang/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/AFNetworking -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/CocoaLumberjack -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/Lock -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/Masonry -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/SimpleKeychain -L/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/TouchIDAuth -F/tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator -filelist /tmp/pepperoni-app-kit/ios/build/Build/Intermediates/PepperoniAppTemplate.build/Debug-iphonesimulator/PepperoniAppTemplate.build/Objects-normal/x86_64/PepperoniAppTemplate.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.0 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lc++ -ObjC -lAFNetworking -lCocoaLumberjack -lLock -lMasonry -lSimpleKeychain -lTouchIDAuth -framework CoreGraphics -framework Foundation -framework LocalAuthentication -framework MobileCoreServices -framework Security -framework SystemConfiguration -framework UIKit -framework WebKit -fobjc-arc -fobjc-link-runtime /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libReact.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTImage.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTLinking.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTSettings.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTText.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTVibration.a /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a -lA0RNLock -lPods-PepperoniAppTemplate -Xlinker -dependency_info -Xlinker /tmp/pepperoni-app-kit/ios/build/Build/Intermediates/PepperoniAppTemplate.build/Debug-iphonesimulator/PepperoniAppTemplate.build/Objects-normal/x86_64/PepperoniAppTemplate_dependency_info.dat -o /tmp/pepperoni-app-kit/ios/build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/PepperoniAppTemplate
ld: library not found for -lA0RNLock
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
    Ld build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/PepperoniAppTemplate normal x86_64
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/private/tmp/pepperoni-app-kit/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:475:13)
    at Object.execFileSync (child_process.js:495:13)
    at _runIOS (/private/tmp/pepperoni-app-kit/node_modules/react-native/local-cli/runIOS/runIOS.js:91:28)
    at /private/tmp/pepperoni-app-kit/node_modules/react-native/local-cli/runIOS/runIOS.js:24:1
    at tryCallTwo (/private/tmp/pepperoni-app-kit/node_modules/promise/lib/core.js:45:5)
    at doResolve (/private/tmp/pepperoni-app-kit/node_modules/promise/lib/core.js:200:13)
    at new Promise (/private/tmp/pepperoni-app-kit/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/private/tmp/pepperoni-app-kit/node_modules/react-native/local-cli/runIOS/runIOS.js:23:8)
    at Object.run (/private/tmp/pepperoni-app-kit/node_modules/react-native/local-cli/cliEntry.js:95:11)
    at Object.<anonymous> (/Users/wjiang/.nvm/versions/node/v6.3.0/lib/node_modules/react-native-cli/index.js:88:7)
/tmp/pepperoni-app-kit $
```
### Steps to reproduce the error:
1. `git clone https://github.com/futurice/pepperoni-app-kit`
2. `cd pepperoni-app-kit && npm install`
3. `cp env.example.js env.js`
4. `cd ios && pod repo update && pod install && cd -`
5. `react-native run-ios`
### Versions:
- node: v6.3.0
- npm: v3.10.3
- ruby: v2.3.1
- pod: 1.0.1
- react-native-cli: v1.0.0
- react-native: v0.29.0

**Comment by bryanterrell** [comment]
I actually had the app running in the iOS simulator briefly, but after wiping and trying again I can't seem to get it running - just getting that same error:
`":CFBundleIdentifier", Does Not Exist`

**Comment by jevakallio** [comment]
Yes, I can replicate this. Investigating.

**Comment by ljmsouza** [comment]
I had this problem and solved with the `react-native upgrade` command like that guy commented on [https://github.com/facebook/react-native/issues/7308](url). @jevakallio  thanks for the reference! 😄

**Comment by wujiang** [comment]
@ljmsouza After `react-native upgrade`, the build was successful for me too. Thank you. It's a problem from `react-native` so I'm closing this ticket. Thank you very much for the help guys!

**Comment by jevakallio** [comment]
It's not entirely a react-native issue, Pepperoni should build out of the box. For some reason the PRODUCT_NAME variable binding we use to populate the CFBundleIdentifier field no longer works after the latest upgrade.

I have fixed the issue locally by running react-native upgrade and reapplying our customisation son top of it. I have working version of Pepperoni, but made some unnecessary .pbxproject changes in the process and need to clean up before pushing this up.

I'll reopen until this is fixed in master, so others experiencing the same problem don't get tripped up or resubmit a new one.

**Comment by wujiang** [comment]
Understood. Thank you.

**Comment by simonbdev** [comment]
any ETA on getting this fixed?

FYI - RN version 0.30 was also just released

**Comment by jhabdas** [comment]
@simonbdev I'm going to be the bad guy here and ask never to ask for an ETA on open source software. We've been given something great and, as things are in OSS, it gets fixed when it gets fixed.

**Comment by clauderic** [comment]
Any update on this?

**Comment by jevakallio** [comment]
@clauderic this has just been fixed by https://github.com/futurice/pepperoni-app-kit/pull/94. See the PR for tests to verify that change worked.

If you have trouble with getting the new version working with a fresh clone, let me know.

**Comment by acao** [comment]
Still getting this error on a fresh clone

**Comment by jhabdas** [comment]
@acao did you take the steps shown in #94. Specifically, `(cd ios; pod repo update; pod install)`?

**Comment by steezeburger** [comment]
@jhabdas I also just tried running the ios version and did complete that step and am having the same issues.

**Comment by jhabdas** [comment]
@jevakallio seems this should be reopened

**Comment by krolow** [comment]
I have faced that today

**Comment by AndrewZurn** [comment]
Same, hit the exact same error off a fresh copy (or rather taken yesterday morning) clone of the template.

**Comment by jhabdas** [comment]
RN moves fast. My best suggestion is to slim down your boilerplates, start from an RN init and practice _code for toda_y XP philosophies while building leveraging the [best of the current kits](https://habd.as/awesome-react-boilerplates/#react-native) available. Good luck to all. And I hope to see a new simple starter kit emerge for RN without immutable.

**Comment by AndrewZurn** [comment]
Seems like I was able to fix the issue somehow... not quite sure what I did, attempted a manual linking, and then actually ran `rnpm link react-native-lock` and it seemed to resolve itself.

Here is what the commit ended up looking like.
https://github.com/AndrewZurn/pepperoni-app-kit/commit/367f3cdd69a692a7c948ec5f3004b173f3c9793d

**Comment by krzysztofp** [comment]
Same issue today for a fresh clone, any update on this?

**Comment by tino-junge** [comment]
Hey @krzysztofp, thanks for your interest in pepperoni 🍕 🚀 What steps are you using for a fresh clone? Just checked it out myself and the following steps are working for me. Let me know if you have any issues with these:

```
git clone git@github.com:futurice/pepperoni-app-kit.git
cd pepperoni-app-kit 
yarn  // or `npm install`
(cd ios; pod install)
react-native run-ios
```

**Comment by tino-junge** [comment]
Hi @krzysztofp, we removed now cocoa pods as dependency so you shouldn't get this error anymore when cloning a fresh copy of the repo again. Just run 

```
yarn install
react-native run-ios
```
to get started. Let me know if it solves you issue.

**Comment by tino-junge** [comment]
closing this now since issue doesn't seem to be active anymore

**Comment by fredbt** [comment]
I'm still having this issue (running react-native run-android in a linux box). Not sure if it's a problem that I'm using Linux.
I've just cloned the repo.

**Comment by jhabdas** [comment]
@fredbt perhaps time to open a new ticket?

**Comment by jhabdas** [comment]
use `uname -a` to get the deets about your distro
